import Head from "next/head";

import { SectionBody, Header } from "@/organisms";
import Intro from "@/templates/Intro";

import { SECTIONS_DIR } from "config/paths";
import sectionsMap from "constants/sections-map.json";
import About from "@/templates/About";
import Events from "@/templates/Events";

const Home = () => {
  return (
    <div className="w-full bg-black">
      <Head>
        <title>Cyber-Trace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header sections={sectionsMap.map(({ name }) => name)} />
      <main className="max-w-screen-2xl	 mx-auto grid gap-20">
        <Intro />
        {/* {sectionsMap.map(({ name, title }) => {
          const SectionContent =
            require(`../${SECTIONS_DIR}/${name}.js`).default;
          return (
            <SectionBody key={name} name={name} title={title}>
              <SectionContent />
            </SectionBody>
          );
        })} */}
        <SectionBody key={5} name={"Events"} title={"Our community"}>
          {/* <About /> */}
          <Events />
        </SectionBody>
      </main>
    </div>
  );
};

export default Home;
