import Head from "next/head";
import Image from "next/image";
import ArticleCard from "../components/AtomicCmps/ArticleCard";
import Button from "../components/AtomicCmps/Button";
import EventCard from "../components/AtomicCmps/EventCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black h-screen w-full p-10">
        <Button label="Join us" />
        <EventCard
          img="/image.jpg"
          text="this is an event card"
          title="this is the event text"
        />
      </main>
    </div>
  );
}
